### ISSUE TITLE
AUTO: Revise Odometry Code

### ISSUE THREAD

**Issue by schromya** [UAA-Robo/VEX-U-Over-Under#13]
#### Description
Using the new drivetrain dead wheels and possible error correction, revise the odometery code. This should be done in the AutoDrive and the Telemetry classes. Most position code in  [VexU-Spinup-VexCode repo](https://github.com/UAA-Robo/VexU-Spinup-VexCode) should remain the same. 

### DOD
This task its considered done when it is thoroughly documented in the [Engineering Notebook](https://docs.google.com/document/d/1auSQpJCPH_xxbiL1h6w8SKAvTJxroBNW1Kcgkotj7ro/edit?usp=sharing).

Notes:
https://gm0.org/en/latest/docs/software/concepts/odometry.html
https://file.tavsys.net/control/controls-engineering-in-frc.pdf

**Comment by schromya** [comment]
Sources for math for 3 odometer wheels:
- [odometry video](https://youtu.be/Av9ZMjS--gY?si=mFk93DBMn4BDIh6i)
- [tracking.pdf](http://thepilons.ca/wp-content/uploads/2018/10/Tracking.pdf)
- [kinematics_for_ftc.pdf](https://github.com/acmerobotics/road-runner/blob/master/doc/pdf/Mobile_Robot_Kinematics_for_FTC.pdf)
- [reddit post](https://www.reddit.com/r/FTC/comments/d5mmdl/odometry_math/)

**Comment by schromya** [comment]
Jaren's suggestions: dead reckoning, differential drives, acronym steering, non-fixed odometer wheel

**Comment by schromya** [comment]
Got thread structure and basic math working but giving odd values so need to debug

![Image](https://github.com/UAA-Robo/VEX-U-Over-Under/assets/80082701/ef242681-a218-4cd5-8a1d-ef30228dd970)
![Image](https://github.com/UAA-Robo/VEX-U-Over-Under/assets/80082701/e6ee91de-4a5d-416c-9f49-bc5f9d881fda)

**Comment by schromya** [comment]
Debugged most of code yesterday, x position seems good but y position is buggy. May be heading error.

**Comment by schromya** [comment]
[Another Source](https://gm0.org/en/latest/docs/software/concepts/odometry.html)

**Comment by pixama** [comment]
The x/y- positions are not accurate. Nor the heading.

**Comment by schromya** [comment]
Implemented [this](https://gm0.org/en/latest/docs/software/concepts/odometry.html) and got it approximately working.  Also tried deriving them ourselves and got the relative robot's change in x, change in heading. But not the robot's relative change in y or the overall change in robots position.

![Image](https://github.com/UAA-Robo/VEX-U-Over-Under/assets/80082701/f723e20a-4d92-4bc7-b242-c0a0a9c7aa4f)

**Comment by schromya** [comment]
Wa Worked on documentation in for the engineering notebook yesterday.

**Comment by pixama** [comment]
if the num > denominator, and the results are small, it's rounded down to zero. Maybe we can convert to degrees (heading and heading_displacement) before modding? I don't know how well that'll work :))

**Comment by pixama** [comment]
Have the odometry functions and code (to differentiate robots). Waiting to test on drivetrain. Also have to set  drivetrain dimensions after odometry wheel is implemented in design :))

It builds... for now.

**Comment by pixama** [comment]
Tested the bot. Turns in the correct directions, and it moves.

But it won't stop, which I figured is probably because spin() is non-blocking, so the distance is never reevaluated. I'm considering a different approach using spinFor() again :))

**Comment by schromya** [comment]
Odemetry works for small bot.
