### ISSUE TITLE
USERDRIVE: Macros

### ISSUE THREAD

**Issue by Dawson-Packer** [UAA-Robo/VEX-U-Over-Under#16]
### Description

Create a way to save user-controls and "play" the back to control the robot.

### DOD

This task its considered done when it is thoroughly documented in the [Engineering Notebook](https://docs.google.com/document/d/1auSQpJCPH_xxbiL1h6w8SKAvTJxroBNW1Kcgkotj7ro/edit?usp=sharing).

**Comment by Dawson-Packer** [comment]
The macro system involved rerouting controller inputs to class UserDrive private variables, and calling a getInputs() function at the start of every instance of drive(). All user-controlled action functions like drivetrain_controls() then pull inputs from those generic private variables, allowing manipulation of controller inputs values (possible corrective-actions). Macros are currently implemented, but the copy movement is not identical. Further testing will prove whether the controller inputs recorded differ (export to SD card for analysis), or a mechanical issue (maybe the asymmetrical odometry wheel?).

**Comment by schromya** [comment]
Revised and Approved to be merged into main.
